const Data = [
  {
    id: "1",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    country: 'Costa Rica',
    countryFlag: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQQAAACcCAMAAACulCWiAAAAFVBMVEX///8AFInaKRwAD4ggJYz5+fvWAACH5jEyAAAA9klEQVR4nO3d2wkDQRADwZX8yD9kH4rBcMZURTD0/6ATcu4+4BeIEBFGhIgwIkSEESEijAgRYUSICCNCRBgRIsKIEBFGhIgwIkSEOQ8e58nzvHgdAAAAAAAAvujN+5SKUBFGhIowIlSEEaEijAgVYUSoCCNCRRgRKsKIUBFGhIowIlSEEaEijAgVYUSoCCNCRRgRKsKIUBFGhIowIlSEEaEijAgVYUSoCCNCRRgRKsKIcPH+c7n7BQsAAAAAAOC/3D0/9AuMYV3Mol0M5MVK4IgQEUaEiDAiRIQRISKMCBFhRIgII0JEGBEiwogQEUaEiDAiRIT5APc8uuE9qw01AAAAAElFTkSuQmCC',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1200px-Paris_Saint-Germain_Logo.svg.png',
    atCurrentClubSince: '2019',
    position: "Gardien de but",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "2",
    jerseyNumber: '30',
    firstname:"Alexandre",
    lastname:"Letellier",
    age: '32',
    dateOfBirth: '11/12/1990',
    height: '1,93m',
    country: 'France',
    countryFlag: 'https://cdn-icons-png.flaticon.com/128/5921/5921991.png',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1200px-Paris_Saint-Germain_Logo.svg.png',
    currentClubColor: '#151e2d',
    atCurrentClubSince: '2020',
    position: "Gardien de but",
    appearancesForCurrentClub: '2',
    goalsConcededForCurrentClub: '0',
    cleanSheetsForCurrentClub: '0',
    photo: "https://www.psg.fr/media/187967/cards-23-24_letellier-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"

  },
  {
    id: "3",
    jerseyNumber: '80',
    firstname:"Arnau",
    lastname:"Tenas",
    age: '22',
    dateOfBirth: '30/05/2001',
    height: '1,85m',
    country: 'Espagne',
    countryFlag: 'https://cdn-icons-png.flaticon.com/128/10601/10601048.png',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1200px-Paris_Saint-Germain_Logo.svg.png',
    atCurrentClubSince: '2017',
    position: "Gardien de but",
    appearancesForCurrentClub: '0',
    goalsConcededForCurrentClub: '0',
    cleanSheetsForCurrentClub: '0',
    photo: "https://www.psg.fr/media/27048/cards-23-24_mbappe.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "4",
    jerseyNumber: '27',
    firstname:"Keylor",
    lastname:"Navas",
    age: '28',
    dateOfBirth: '12/07/1995',
    height: '1,68m',
    currentClub: 'Nantes',
    currentClubLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Logo_FC_Nantes_%28avec_fond%29_-_2019.svg/1589px-Logo_FC_Nantes_%28avec_fond%29_-_2019.svg.png',
    atCurrentClubSince: '2019',
    position: "Millieu de terrain",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.fcnantes.com/images/joueurs/20232024/illu200x120/SIMON.png"
    
  },
  {
    id: "5",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "6",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "7",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "8",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "9",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "10",
    jerseyNumber: '1',
    firstname:"Keylor",
    lastname:"Navas",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
    
  },
  {
    id: "1",
    jerseyNumber: '1',
    firstname:"Kylian",
    lastname:"Mbappé",
    age: '36',
    dateOfBirth: '15/12/1986',
    height: '1,85m',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://e7.pngegg.com/pngimages/432/997/png-clipart-paris-saint-germain-logo-paris-saint-germain-f-c-paris-saint-germain-academy-france-ligue-1-paris-fc-parc-des-princes-paris-emblem-trademark.png',
    atCurrentClubSince: '2019',
    position: "GoalKeeper",
    appearancesForCurrentClub: '108',
    goalsConcededForCurrentClub: '87',
    cleanSheetsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/33317/cards-23-24_navas-alt.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
  },
  {
    id: "",
    jerseyNumber: '7',
    firstname:"Kylian",
    lastname:"Mbappé",
    age: '24',
    dateOfBirth: '20/12/1998',
    height: '1,78m',
    country: 'France',
    countryFlag: 'https://cdn-icons-png.flaticon.com/128/5921/5921991.png',
    currentClub: 'Paris Saint-Germain',
    currentClubLogo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1200px-Paris_Saint-Germain_Logo.svg.png',
    atCurrentClubSince: '2017',
    position: "Attaquant",
    appearancesForCurrentClub: '268',
    goalsForCurrentClub: '220',
    assistsForCurrentClub: '50',
    photo: "https://www.psg.fr/media/27048/cards-23-24_mbappe.png?center=0.5,0.5&mode=crop&width=400&height=600&quality=75"
  }
]

export default Data